yogthos/Selmer

- src/selmer/util.clj
At [this point](https://github.com/yogthos/Selmer/blob/ed884bd1bd8206216790f9a913de0cdceb834ecf/src/selmer/tags.clj#L202), suggested in https://github.com/yogthos/Selmer/issues/53,  we do not have all the data -- it is already splitted by space..
Simple solutions should change this code:
```clojure
(let [content (->> (.toString buf)
(check-tag-args)
(re-seq #"(?:[^\s\"]|\"[^\"]*\")+")
(remove empty?)
(map (fn [^String s] (.trim s))))]
```
from [here](https://github.com/yogthos/Selmer/blob/ed884bd1bd8206216790f9a913de0cdceb834ecf/src/selmer/util.clj#L61) by adding something like ```(-> (.toString buf) (.replace "= ") (.replace " ="))``` (not sure if this code correct). Such operation will slow down parsing procedure.
But in my opinion it's not idiomatic to use spaces in such places. For …
> Fixes #53: check for spaces near `=` in param assign.

- src/selmer/util.clj
Current code base will not allow the creation of defaults with include in case the tag close and the filter close are different. This would resolve that.
> Using include parameters where the filter and tag close are different

- README.md
- project.clj
- src/selmer/util.clj
- test/selmer/core_test.clj
My previous contribution to turn off escaping was a bit naive. It changes the root binding of the var that controls escaping. However, if someone wishes to turn escaping on/off in different threads (already running into this), then we need to use (binding). I have included 2 new macros to turn escaping on/off within it's body.
> Better way of turning off escaping.

- README.md
- project.clj
- src/selmer/filter_parser.clj
- test/selmer/core_test.clj
Filter arguments prefixed with @ are looked up in the context map before
being passed to the filter function. Dot notation (@x.y.z) is
supported. A single @ is treated as a literal argument. If an argument
beginning with @ is not found in the context map, it is treated as a
literal argument (for backward compatibility).
Bumped the project version to 0.9.4 to indicate the new feature (so a
release can be cut a.s.a.p.).
> Add support for @-prefixed filter arguments

- README.md
- src/selmer/parser.clj
- src/selmer/util.clj
- test/selmer/core_test.clj
This is an attempt to close https://github.com/yogthos/Selmer/issues/51. Short-form comment tags like `{# this is a comment #}` will be dropped by the parser.
> Add short-form comment syntax

- src/selmer/node.clj
For ease of debugging, REPL interaction etc, add toString
implementation for TextNode which simply returns the node text.
E.g.
```
;; before:
(TextNode. "foo")
=> #object[selmer.node.TextNode 0x4a55c661 "selmer.node.TextNode@4a55c661"]
;; after:
(TextNode. "foo")
=> #object[selmer.node.TextNode 0x4a55c661 "foo"]
```
> Add toString implementation to TextNode

- README.md
- src/selmer/filter_parser.clj
@yogthos 
Hi - I have changed the regex in filter_parser.clj to allow the function to not split if there is a double dot. This will mean that the string:
foo.bar.baz..daz..maz.raz --> "foo" "bar" "baz..daz..maz" "raz"
but as originally intended:
foo.bar.baz --> "foo" "bar" "baz"
This is needed as if we pull through Datomic dotted namespaces as keys into the data structures presented to Selmer we need to preserve the dot. So by 'double-dotting' in the template we can achieve our goal. Please consider a pull! Thanks for the library, regards Hugh
> changed filter_parser to allow for double dots form of escape

- src/selmer/parser.clj
- test/selmer/core_test.clj
We'd like to get a little more info out of the parser. Would you be amenable to putting tag information in function metadata?
> add tag info to FunctionNode handler metadata

- src/selmer/filters.clj
- src/selmer/parser.clj
- test/selmer/core_test.clj
Our company is allowing users to pass templated strings to have Selmer parse. We only want to support a limited set of filters and tags and this seems like a consistent approach to the ```add-filter!``` and ```add-tag!``` methods
> Remove tags and filters

- src/selmer/parser.clj
- src/selmer/util.clj
Submitted per the proposal in #135. I also included a change to address #134.
Initially, I wanted to bind `*custom-resource-path*` in `parse` since there are other bindings there, but that approach didn't work because `render-file` first calls `check-template-exists`, which relies on the custom resource path. 
Feedback welcome.
> Thread-bound render custom resource path

- src/selmer/parser.clj
- src/selmer/util.clj
- test/selmer/core_test.clj
solves #152 
Allows passing of java.net.URL to render-file.
I am unsure if this feature is worth the performance hit, but I figured I would provide it as it has tripped me up a couple times.
> Fix caching bug and allow render-file to accept java.net.URL as filename

- src/selmer/tags.clj
Currently only a single filter is applied if it is in a for tag.
`user=> (parser/render "{% for x in items|last|last|last|last %}{{x}}{% endfor %}" {:items [1, 2, [3, [4, 5]]]})
"3[4 5]"`
instead it should be `45`
This is because items is a keyword in the context map but the value of items in the apply-filters function is a string. 
When [get-accessor](https://github.com/yogthos/Selmer/blob/master/src/selmer/filter_parser.clj#L137-L143
) is called from [compile-filter-body](https://github.com/yogthos/Selmer/blob/master/src/selmer/filter_parser.clj#L145) it is looking for a keyword but the assoc in apply-filters is just adding a string into the map rather than overriding the keyword. This PR will allow for both string or keyword support.
> Allow for multiple keyword filters in for tag

- src/selmer/parser.clj
- test/selmer/core_test.clj
It happens when render-file opts contains :custom-resource-path
without protocol.
> Fix MalformedURLException in render-file

- README.md
- src/selmer/filters.clj
- test/selmer/core_test.clj
This PR adds the following filters, as well as tests for them:
- multiply
- divide
- round
- drop-last
- between?
- replace
Whenever the underlying Clojure function accepts Long and Double values, a new `parse-number` function is used to parse the number. This applies especially to the `add` filter.
Additionally, all filters returning truthy values or numbers are defined as _safe_ to remove the need to cast them to a string and then back to a number potentially.
> Add multiple filters

- src/selmer/tags.clj
- test/selmer/core_test.clj
This allows the user to easily see which for loop has a missing argument, if
there are many for loops in the template.
Fixes leftover stuff in https://github.com/yogthos/Selmer/issues/165
> Make :for tags call missing-value-formatter with more arguments.

- README.md
- src/selmer/filters.clj
- test/selmer/core_test.clj
As discussed here is a working implementation of an `abbreviate` filter. Originally I thought I can just provide an alternative ellipsis or direction parameter as optional parameters to the filter. But this idea turns out unworkable without making every parameter mandatory. E.g. what should `abbreviate:20:10` mean? Abbreviate a string longer than 20 to 10 or abbreviate to 20 with an Ellipsis string of `10`? Or `abbreviate:20:left`? Is that an ellipsis string `left` or a position option? So i decided to make it simple by having only two parameters (one of them optional) and providing the rest via additional filters, with either no or just one mandatory parameter which solves all ambiguities.
The `prefilters` make some kind of "tagging" of the input string necessary. My first idea to do it …
> Add abbreviate filter (follow up from #162)

- README.md
Add a quick reference to `selmer.utils/*escape-variables*` by the `safe` tag.
> Add a reference to selmer.utils/*escape-variables* to README

- README.md
- src/selmer/filters.clj
- test/selmer/core_test.clj
Hi
After some thought I've added a second positional parameter to the `phone` tag to allow defaulting ot the international subscriber dialling prefix; this seems the solution best in keeping with your practice. I've also supplied documentation in the `README.md`, and additional unit tests to cover the added functionality.
I hope this will be satisfactory!
> Using positional parameter for default national dialing code

- src/selmer/filter_parser.clj
- src/selmer/parser.clj
- src/selmer/tags.clj
- test/selmer/benchmark.clj
- test/selmer/core_test.clj
Mostly these are misplaced doc strings, or missing (is ...)
expressions around unit tests.  There were also 3 deftests with
identical names, which silently causes all but one of them not to have
their tests run.
> Fix some warnings found by Eastwood linter

- project.clj
Since selmer is clj-only, its use of json-html may not need to pull in hiccups (with its clojurescript dependencies).
> Exclude hiccups from json-html

- src/selmer/filters.clj
- test/selmer/core_test.clj
Recent changes (bef524b96a634d68a2aa02db1a757e4d67b0c26c) rendered the `date` filter less friendly to locales by enforcing format strings rather than using built-in locale-aware formats for dates / times. Using the named, built-in formats allows for proper expression of localized dates / times, which may not naturally follow the same component order as (e.g.) a format string that is natural for English.
A salient example would be rendering 2014-03-01 into Chinese (`"{{d|date:longDate:zh}}"`); prior to this code change, the result is `三月 01, 2014` (which is super odd if, *arguably*, comprehensible) rather than the much more natural `2014年3月1日` yielded after the patch.
In the interests of not assuming the reader is familiar with Chinese, it's likely enough to explain that Chinese dates are …
> Render dates in locale-aware fashion

- README.md
Captures some of the nuances we discussed in #190.
> README.md: details about behavior of `date` filter

- src/selmer/tags.clj
- test/selmer/core_test.clj
Documentation provides the following example of escaping dots in qualified keywords:
`(parser/render "{{foo..bar/baz}}" {:foo.bar/baz "hello"})`
Unfortunately this does not work for qualified keywords used as arguments of `for` tag (please see the test I added in this PR.)
(Edit: I can't believe I missed the issue that already exists. Sorry!)
Fixes #138
Over time, splitting of arguments on dots seems to have been introduced independently in two separate functions. One of those has been modified to allow qualified keywords (`selmer.filter-parser/split-filter-val`) and one has not (`selmer.tags/parse-arg`.)
I copied the solution from `selmer.filter-parser/split-filter-val` to `selmer.tags/parse-arg` in order to preserve consistency.
It looks like the solution should be a shared piece of …
> Fix: for tag accepts qualified keywords

- README.md
The current description for the `replace` filter in the readme is currently a duplicate of the description of the `multiply` filter
>  Update `replace` filter description in readme

- src/selmer/tags.clj
- test/selmer/core_test.clj
For example,
```
(render "{% with math=\"1+1=1\" %}{{ math }}{% endwith %}" {})
```
used to throw an error, but now it should be fine.
Fixes https://github.com/yogthos/Selmer/issues/211
> Make the with tag support = sign in quoted variables.

- src/selmer/util.clj
- test/selmer/core_test.clj
I also replaced a deprecated call of `(.toURL f)` with `(.toURL (.toURI f))`, which is now the recommended way.
> Fixed unit tests for Windows line separators and file paths.

- src/selmer/validator.clj
Hi @yogthos,
Thanks for a great library.
This PR just fix the name of the function from `valide-tag` to `validate-tag`.
Please feel free to adjust anything if you like.
Thanks
> Rename valide to validate for function name

- src/selmer/parser.clj
- test/selmer/core_test.clj
Fixes bugs like:
```
(selmer/render "{% if a %} some text {# comment! #} {% endif %}" {:a true})
=> " some text {# comment! #} "
```
(issue https://github.com/yogthos/Selmer/issues/220)
To fix this we need to do an initial pass to remove all short form comments -
this can be done in the initial parsing of the template file/string
and then memoized.
I'm not 100% sure about the performance goals here - doing a simple regex
like
```
(defn parse* [input]
(let [input-string     (slurp input)
comments-removed (string/replace input-string #"\{#.*?#\}" "")
rdr              (io/reader (char-array comments-removed))]
```
would have been easier but required twice the memory for the string I guess?
Still, it feels a little weird to do such optimization when the string
still has to be written to …
> Fix a bug with short form comments not working inside tags.

- README.md
- src/selmer/filter_parser.clj
- src/selmer/parser.clj
- src/selmer/tags.clj
- src/selmer/util.clj
- test/selmer/core_test.clj
Fixes https://github.com/yogthos/Selmer/issues/109
You can now have elif clauses in your ifs.
So, annoying code like this:
```
{% if a > 100 %}
{% if a > 9000 }
it's over 9000!
{% else %}
it's in a middle zone
{% endif %}
{% else %}
{% if a > 10 }
still over ten.
{% else %}
lower than 10.. sad
{% endif %}
{% endif %}
```
can now be un-nested and made more readable like this:
```
{% if a > 9000 %}
it's over 9000!
{% elif a > 100 %}
it's in a middle zone
{% elif a > 10 %}
still over ten.
{% else %}
lower than 10.. sad
{% endif %}
```
This was quite a doozy but it's easter holiday in quarantine so great for open source! I think the new code turned out a lot nicer than I expected and it was less of a pain to do than expected as well. 
It currently not very generic - I've hard-coded the elif …
> Elif (else if) support

- README.md
- src/selmer/tags.clj
- test/selmer/core_test.clj
The main point of this is to enable more complex logic if else logic, now that
the elif tag exists and you might want to have some stanzas compare
numbers and some compare strings (or whatever)
(I Realized that in most cases I found where I need to use the elif tag 
it's actually for strings... 🤦‍♂️)
It makes the code a bit more complex unfortunetly.. Please let me know what you think @yogthos! And sorry to keep bothering you so much :)
> Allow comparing strings and keywords in the if tag like so {% if x = :lol %}.

- src/selmer/tags.clj
- test/selmer/core_test.clj
For example,
`(render "{% if x = y %}doublenil{% endif %}" {})` did not work - this
bug was introduced in 7e8d and it used to work before that.
Sorry about that!
> Fix a nullpointerException when comparing null in the if tag.

- src/selmer/tags.clj
- test/selmer/core_test.clj
- test/templates/elif.html
Hi again! :)
Using multiple elif clauses in the same if did not
work in file temaplates, only string ones. If you tried it
you got a "no closing tag found" error.
I'm not 100% sure why it worked for strings to begin with..
But anyhow the fix was that the elif tag needed to have itself as a closing
tag.
> Fix a bug with elif tags in files.

- project.clj
- src/selmer/parser.clj
- src/selmer/util.clj
In addition to considering paths that begin with the system file separator, when on Windows one also has to consider paths that begin with a drive letter followed by a colon.
It seems to work fine both on the Mac and Windows now.
> This seems to fix the use of templates on Windows, #231

- src/selmer/tags.clj
- test/selmer/core_test.clj
Example:
`{% with math.math=\"1+1=2\" %}{{ math.math }}{% endwith %}`
> Add nested assignment to with-tags

- src/selmer/tags.clj
- test/selmer/core_test.clj
Does not update the README to document this new option -- I wasn't sure how you handled documentation of new features that have not yet been released.
This precomputes the value mappings for `items` so that it can avoid recomputing them for `previous` inside the loop.
I updated the only test that broke -- I did not add a specific test for this new functionality but I would be happy to do so if you would prefer.
I'm also happy to submit the PR from a branch if you'd prefer that.
> Fixes #243 by adding forloop.previous

- src/selmer/tags.clj
- src/selmer/util.clj
- test/selmer/benchmark.clj
- test/templates/any.html
- test/templates/numerics.html
Helps a lot with https://github.com/yogthos/Selmer/issues/245, altough I will keep digging further.
I've added an if-bench benchmark, and taken it down from ~145ms to ~30ms.
The main culpit for the slowness was fix-accessor, which was using exception handling
to parse integers. Exceptions are expensive, at least when you use them
a couple of thusand times:
```
((time (dotimes [_ 100000] (try (Long/valueOf "nan")
(catch NumberFormatException _))))
"Elapsed time: 219.507474 msecs"
(time (dotimes [_ 100000] (when (re-matches #"\d+" "nan") (Long/valueOf "nan"))))
"Elapsed time: 11.263704 msecs"
```
```
BENCH: Many . acceses in an if clause
Evaluation count : 6 in 6 samples of 1 calls.
Execution time mean : 145.789759 ms
Execution time std-deviation : 3.397597 ms
Execution time lower quantile …
```
> Speed up filter accesses like {% if a.b.c.d %}.

- src/selmer/parser.clj
- src/selmer/util.clj
- test/selmer/core_test.clj
The java.net.URL class supports the inclusion of a custom 'stream handler'. This
allows the user to override how URLs are loaded. When combined with
a *custom-resource-path*, this allows templates to be sourced from anywhere the
user likes. Example includes databases, external caches and networked services.
This change introduces a new dynamic var which, if set, allows the user to provide the `java.net.URLStreamHandler`, directing requests for templates to custom code. The implementation of this stream handler by the user is not particularly ergonomic (as shown in the test), but at least makes it _possible_ to do so.
I'm happy to work on making it more ergonomic, perhaps by allowing a function to take the place of the stream handler, at the (possibly small) expense of reducing the range …
> Add support for java.net.URLStreamHandler

- project.clj
- src/selmer/tags.clj
- src/selmer/util.clj
- test/selmer/core_test.clj
This commit makes the json-html dependency (and its dependencies) optional.
It also fixes some reflection warnings.
> [#253] Make json-html dependency optional

- src/selmer/filter_parser.clj
- src/selmer/util.clj
- test/selmer/core_test.clj
Is there a reason we can't have some whitespace in filters?
``` clojure
(= "bar" (render "{{ foo | default:bar }}" {:dude 1}))
```
This PR makes this possible. Please merge with care. I'm not sure if I will introduce any ambiguity in the syntax that cannot be fixed later.
> Whitespace cosmetics

- src/selmer/parser.clj
- test/selmer/core_test.clj
includes tests.
fixes the case where:
```
(def x 1)
(let [x nil] (<< "{{x}}"))
```
was returning "1" instead of "" because it would skip over x in the local env.
> string-interpolation should work with falsey env

- src/selmer/parser.clj
This might be necessary for some static generation tools which need to alternate the opening & closing tags in nested files.
> add `opts` to `known-variables` params, to parity w/ `render`

- src/selmer/parser.clj
remove condition logic for handling non-path cases and instead always output paths.
parser/known-variables now strips off the head of returned path seqs and returns that.
this logic was previously in parse-variables.
> REFACTOR parser/parse-variables

- src/selmer/tags.clj
- test/selmer/core_test.clj
Fixes #150 
We use a backslash to denote the starting of a numeric literal. Feedback is welcome.
> feat: `sum` tag handles numeric literals
