src/selmer/parser.clj, src/selmer/util.clj, test/selmer/core_test.clj
=> make custom-resource-path a dynamic var

README.md, src/selmer/tags.clj, test/selmer/core_test.clj
Added a new built-in tag 'sum' which when called returns
the sum of the list of variables given.
=> Added new built-in tag 'sum'

README.md, docs/uberdoc.html, src/selmer/filters.clj, test/selmer/core_test.clj
...instead of the hardcoded "en" locale
=>  Use the default locale for the instance of the JVM

README.md, src/selmer/filters.clj, test/selmer/core_test.clj
I've found this to be useful when taking clojure data and applying them to html templates. Seems nice to provide as a built-in.
=> Add a name filter to the built-ins.

README.md, src/selmer/filter_parser.clj, test/selmer/filter_parser_test.clj
As per conversation on issue #54
=> Add support for string keys in filter accessors

src/selmer/tags.clj, test/selmer/core_test.clj
This is my naive attempt to fix #82. 
I also added some test.
=> issue #82, now ifequal supports keywords

README.md, src/selmer/filters.clj
Found myself repeatedly implementing these, figured it might help others.
=> implement take and drop as built-in filters

src/selmer/filters.clj
=> Fix Cast error in take/drop filters

src/selmer/filter_parser.clj, test/selmer/core_test.clj
Maybe the test is in the wrong place...
=> Issue #145, string-based keys with slash recognized 

src/selmer/parser.clj
As mentioned in #152 changed argument name to more accurately reflect changes in #153
=> Rename render-file argument to reflect changes in PR #153

src/selmer/filter_parser.clj, test/selmer/core_test.clj
Minor change, will be helpful in case readers need to figure out at which point do things get escaped.
=> Expanded documentation around safe filters, added tests as demo

src/selmer/tags.clj, test/selmer/core_test.clj
Fixes issue https://github.com/yogthos/Selmer/issues/165
=> Make the for tag respect missing-value-formatter.

README.md
Relates to https://github.com/yogthos/Selmer/issues/165
=> Update readme, now mentions missing value handling for empty for loops

README.md, src/selmer/filters.clj, test/selmer/core_test.clj
This allows positional parameters to be supplied in either order.
=> Email phone filters

src/selmer/filters.clj, test/selmer/core_test.clj
I found two reflection warnings on master, here's a quick fix.
If there's an issue with these please advise.
=> Resolve reflection warnings

src/selmer/parser.clj, src/selmer/template_parser.clj, src/selmer/util.clj
=> Revert "Support template files in depended JAR file (#176)"

src/selmer/parser.clj, src/selmer/template_parser.clj, src/selmer/util.clj
Fixed below uberjar issue.
https://github.com/yogthos/Selmer/pull/205#issuecomment-527660309
=> Support template files in depended JAR file (#176)

src/selmer/filter_parser.clj, src/selmer/parser.clj, src/selmer/util.clj, test/selmer/core_test.clj
=> Adds a function to return all variables

src/selmer/parser.clj, test/selmer/core_test.clj
- adds tests for local var, aliased var, and unaliased var
=> introduce string interpolation macro

deps.edn
needs to be fully-qualified function (sorry!)
=> fix prep function

src/selmer/parser.clj, test/selmer/core_test.clj
similar to known-variables except it outputs paths, as opposed to the top level variable name
the paths can be used in `(get-in obj path)` or `(->> paths (map (partial get-in obj)))`
also "with" testing was missing, so that is now added for known-variables and known-variable-paths
for issue #283
=> ADD known-variable-paths function to selmer.parser

src/selmer/filter_parser.clj, src/selmer/filters.clj, src/selmer/parser.clj, src/selmer/tags.clj, src/selmer/util.clj
=> [#25] Migrate to ex-info, pass exception cause

src/selmer/tags.clj, test/selmer/core_test.clj
fix #300 by adding optional - at start of num? regex.
Also adds two tests for this (confirmed they failed before the fix).
=> fix #300 by updating num? regex

.gitignore, deps.edn, src/selmer/filters.clj, test/selmer/core_test.clj
Signed-off-by: Sean Corfield <sean@corfield.org>
=> fixes #308 by adding support for java.time.Instant in date filter

src/selmer/parser.clj, test/selmer/core_test.clj
And also auto clear it when calling cache-off!
As discussed in https://github.com/yogthos/Selmer/issues/312#issuecomment-2627823172
=> Add a function to clear the cache
